---
- name: Set some initial facts
  ansible.builtin.set_fact:
    caddy_path: "/opt/docker/caddy"

- name: Create caddy network
  community.docker.docker_network:
    name: caddy

- name: Create Caddy directory
  ansible.builtin.file:
    path: "{{ caddy_path }}"
    state: directory
    mode: 0755

- name: Create Caddyfile
  ansible.builtin.file:
    path: "{{ caddy_path }}/Caddyfile"
    state: touch
    mode: 0644

- name: Put VPN restriction snippet in Caddyfile
  ansible.builtin.blockinfile:
    marker: "# {mark} VPN restriction snippet"
    path: "{{ caddy_path }}/Caddyfile"
    block: |
      (restricted_to_vpn) {
        @denied not remote_ip 172.18.0.0/24 {{ greenlist_ips|join(' ') }}
        abort @denied
      }
  notify: restart Caddy

- name: Create Caddy container
  community.docker.docker_container:
    name: caddy
    image: caddy:latest
    pull: true
    state: started
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "{{ caddy_path }}/Caddyfile:/etc/caddy/Caddyfile"
#      - "{{ caddy_path }}/site:/srv"
      - /var/www:/srv
      - /var/run/php:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - name: caddy
    restart_policy: unless-stopped
  